.TH STEELBX "1" "2025-01-01" "steelbx 0.1.0" "User Commands"
.SH NAME
steelbx \- run unsupervised workloads in isolated podman containers
.SH SYNOPSIS
.B steelbx
[\fIOPTIONS\fR] \fICOMMAND\fR [\fIARGS\fR]
.SH DESCRIPTION
.B steelbx
is a tool to run unsupervised workloads in isolated podman containers
with security profiles.
.SH OPTIONS
.TP
.B \-h, \-\-help
Print help information.
.TP
.B \-V, \-\-version
Print version information.
.SH SEE ALSO
.BR podman (1)
